[major] Change the minimum width of the result of "Shift Right" for UInt to 0-bit
chipsalliance/firrtl-spec pull request #164
Opened 2024-01-23 18:04 UTC by SpriteOvO

Change the minimum width of the result of "Shift Right" to 0-bit to align the behavior between Chisel and CIRCT.

Context: https://github.com/chipsalliance/chisel/pull/3752#issuecomment-1905086931, https://github.com/chipsalliance/chisel/pull/3752#issuecomment-1906225248 and chipsalliance/chisel#3735.

2024-01-23 23:15 UTC, dtzSiFive commented
The text that follows says:

> If n is greater than or equal to the bit-width of e, the resulting value will be zero for unsigned types and the sign bit for signed types.
n must be non-negative.

Which suggests maybe the table should still have `1` for the `SInt` case?

Consider:

```
circuit SIntShr:
  module SIntShr:
    input in: SInt<5>
    output out: SInt
    out <= shr(in, 8)
```

Which feeding through `firtool` produces:

```
// Generated by CIRCT firtool-1.63.0g20240122_ce27439
module SIntShr(
  input  [4:0] in,
  output       out
);

  assign out = in[4];
endmodule
```

2024-01-23 23:52 UTC, jackkoenig commented
Good catch @dtzSiFive, I agree. The analogy with `tail` is good, but `tail` on an `SInt` returns `UInt` whereas `shr` on an `SInt` returns `SInt` and as such should preserve the sign bit.

2024-01-26 00:12 UTC, jackkoenig requested changes
After offline discussion with @darthscsi, @seldridge, and @dtzSiFive, we think the best course of action is to change just UInt to have a minimum width of 0 and keep SInt with a minimum width of 1 to maintain mathematical soundness with what it means to do an arithmetic shift to a signed number.

2024-01-26 00:12 UTC, jackkoenig commented on revision-history.yaml
> +      - Change the minimum width of the result of "Shift Right" to 0-bit.
```suggestion
      - Change the minimum width of the result of "Shift Right" on UInt to 0-bit.
```

2024-01-26 00:12 UTC, jackkoenig commented on spec.md
> +                                  (SInt)      SInt          max(w~e~-n, 0)
```suggestion
                                  (SInt)      SInt          max(w~e~-n, 1)
```

2024-01-26 22:22 UTC, SpriteOvO commented
> we think the best course of action is to change just UInt to have a minimum width of 0 and keep SInt with a minimum width of 1 to maintain mathematical soundness with what it means to do an arithmetic shift to a signed number.

Makes sense to me, changes applied.

2024-01-26 22:26 UTC, jackkoenig approved these changes

2024-01-26 22:36 UTC, merged

2024-01-26 23:57 UTC, seldridge reviewed
Thanks for working with us to figure out the right thing to do here. 👍